name: Exemplo de Ação

on:
  push:
    branches:
      - main

jobs:
  exemplo_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Usar segredos
      run: |
        # Acesse os segredos durante a execução da ação
        DB_USER=${{ secrets.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_HOST=${{ secrets.DB_HOST }}
        DB_PORT=${{ secrets.DB_PORT }}
        DB_DATABASE=${{ secrets.DB_DATABASE }}

    - name: Debug variáveis de ambiente
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}"
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
        echo "DB_HOST=${{ secrets.DB_HOST }}"
        echo "DB_PORT=${{ secrets.DB_PORT }}"
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}"

        # Use os segrDB_USERedos no seu código Python
        python -c "import os; print('Conectando ao banco de dados:', os.environ.get('DB_USER'), os.environ.get('DB_PASSWORD'), os.environ.get('DB_HOST'), os.environ.get('DB_PORT'), os.environ.get('DB_DATABASE'))"
